import logging
import os
from datetime import datetime

from dotenv import load_dotenv
from google.oauth2 import service_account
from googleapiclient.discovery import build

load_dotenv()

logger = logging.getLogger(__name__)

SCOPES = [
    "https://www.googleapis.com/auth/drive",
    "https://www.googleapis.com/auth/documents",
]

PLAN_OUTPUT_FOLDER_ID = "11eYr6RIieuw4EvCZCzaMBa8ib8llDr9-"
DRIVE_FILE_BASE_URL = "https://docs.google.com/document/d/"


def _get_services():
    creds_path = os.environ.get("GOOGLE_DRIVE_CREDENTIALS", "./service_account.json")
    creds = service_account.Credentials.from_service_account_file(creds_path, scopes=SCOPES)
    drive_service = build("drive", "v3", credentials=creds)
    docs_service = build("docs", "v1", credentials=creds)
    return drive_service, docs_service


def _build_doc_requests(query: str, answer: str, citations: list[dict]) -> list[dict]:
    """Build Docs API batchUpdate requests to populate the document."""
    today = datetime.now().strftime("%Y-%m-%d")

    sources_text = "\n".join(
        f"- {c.get('title', 'Unknown')} ({c.get('date') or 'n/a'})"
        for c in citations
    )
    footer = f"\nGenerated by progsu Intelligence Agent on {today}"

    full_text = (
        f"Based on: {query}\n\n"
        f"{answer}\n\n"
        f"Sources Referenced\n"
        f"{sources_text}\n"
        f"{footer}"
    )

    requests = [
        {
            "insertText": {
                "location": {"index": 1},
                "text": full_text,
            }
        },
        # Style the first line as a heading
        {
            "updateParagraphStyle": {
                "range": {"startIndex": 1, "endIndex": len(f"Based on: {query}") + 1},
                "paragraphStyle": {"namedStyleType": "HEADING_1"},
                "fields": "namedStyleType",
            }
        },
    ]
    return requests


def create_google_doc(
    query: str,
    answer: str,
    citations: list[dict],
    folder_id: str = PLAN_OUTPUT_FOLDER_ID,
) -> str:
    """
    Create a Google Doc in Drive with the plan content.
    Returns the public URL of the created document.
    """
    today = datetime.now().strftime("%Y-%m-%d")
    title = f"[AI Generated] {query[:60].rstrip()} - {today}"

    try:
        drive_service, docs_service = _get_services()

        # Create empty Google Doc in the target folder
        file_meta = {
            "name": title,
            "mimeType": "application/vnd.google-apps.document",
            "parents": [folder_id],
        }
        file = drive_service.files().create(body=file_meta, fields="id").execute()
        doc_id = file["id"]

        # Populate the document with content
        requests = _build_doc_requests(query, answer, citations)
        docs_service.documents().batchUpdate(
            documentId=doc_id,
            body={"requests": requests},
        ).execute()

        doc_url = f"{DRIVE_FILE_BASE_URL}{doc_id}/edit"
        logger.info("Created Google Doc: %s (%s)", title, doc_url)
        return doc_url

    except Exception as e:
        raise RuntimeError(f"Google Doc creation failed: {e}") from e
